name: Tests

on: push

env:
  SHA: ${{ github.sha }}
  BRANCH: ${{ github.ref }}
  YELLR_KEY: ${{ secrets.YELLR_KEY }}
  YELLR_URL: ${{ secrets.YELLR_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.3.1
    - name: Cache Gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: Install Gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rspec
    - name: Report Failure
      if: failure()
      env:
        STATUS: failing
      run: |
        chmod +x ./script/report_to_yellr.sh
        ./script/report_to_yellr.sh
    - name: Report Success
      if: success()
      env:
        STATUS: passing
      run: |
        chmod +x ./script/report_to_yellr.sh
        ./script/report_to_yellr.sh